# Generated by Django 4.2.15 on 2024-08-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='manager',
            new_name='head_of_department',
        ),
    ]
