# Generated by Django 4.2.15 on 2024-08-20 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_branch_manager'),
        ('accounts', '0003_rename_manager_department_head_of_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseentity',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='baseentity',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseentity',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.branch'),
        ),
        migrations.AddField(
            model_name='baseentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseentity',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseentity',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseentity',
            name='entity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.entitytype'),
        ),
        migrations.AddField(
            model_name='baseentity',
            name='first_name',
            field=models.CharField(default='kofi', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseentity',
            name='full_name',
            field=models.CharField(default='kofi adoma', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseentity',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='baseentity',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseentity',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseentity',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='baseentity',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='baseentity',
            name='last_name',
            field=models.CharField(default='adoma', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseentity',
            name='password',
            field=models.CharField(default='12345', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseentity',
            name='phone_number',
            field=models.CharField(default='3894893493', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseentity',
            name='tax_identifier_number',
            field=models.CharField(default='lsdkfskfjs', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='baseentity',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='baseentity',
            name='username',
            field=models.CharField(default='kadoma', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
