# Generated by Django 4.2.15 on 2024-08-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_baseentity_email_token_baseentity_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseentity',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='baseentity',
            name='password_reset_token',
        ),
    ]
