# Generated by Django 4.2.15 on 2024-08-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_baseentity_email_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseentity',
            name='is_verified',
        ),
    ]
