# Generated by Django 4.2.15 on 2024-08-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver_balance',
            new_name='recipient_account_balance',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sender_balance',
            new_name='sender_account_balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver_account',
        ),
        migrations.RemoveField(
            model_name='transactiondirection',
            name='direction_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='core.account'),
        ),
        migrations.AddField(
            model_name='transactiondirection',
            name='direction',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.FloatField(default=80),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='core.account'),
        ),
    ]
