# Generated by Django 4.2.15 on 2024-08-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_baseentity_options_baseentity_address_and_more'),
        ('core', '0002_branch_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='entity',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to='accounts.employee'),
        ),
    ]
