# Generated by Django 4.2.15 on 2024-08-26 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_receiver_balance_transaction_recipient_account_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='entity',
            new_name='action_initiator',
        ),
        migrations.AddField(
            model_name='account',
            name='created_by',
            field=models.ForeignKey(default='1b9f04ae-a33b-45ee-98bb-0a1f7ca0a131', on_delete=django.db.models.deletion.CASCADE, related_name='created_accounts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
