# Generated by Django 4.2.15 on 2024-08-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_entity_audit_action_initiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient_account_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_account_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
